### ISSUE TITLE
/api/updateChargeConfigInfo returning 404 Not Found error

### ISSUE THREAD

**Issue by nugget100** [alphaess-developer/alphacloud_open_api#59]
Receive a 404 "Not Found" error when connecting to the /api/updateChargeConfigInfo endpoint.  
This has been happening for the last few days since the update as it worked perfectly for months before then.

**Comment by Gaspode69** [comment]
I can confirm this issue.

**Comment by ElevenFan** [comment]
Azure error

**Comment by Gaspode69** [comment]
@ElevenFan 
Why do you close this issue? It has not been solved at all, yet.

**Comment by nugget100** [comment]
This should not have been closed as the issue is still active.
{'timestamp': '2024-01-05T08:20:11.954+00:00', 'status': 404, 'error': 'Not Found', 'path': '/api/updateChargeConfigInfo'}

**Comment by ElevenFan** [comment]
It may be a URL path problem

**Comment by Gaspode69** [comment]
> It may be a URL path problem

What do you mean? Exactly the same URL path worked a few days before!

**Comment by ElevenFan** [comment]
![lQLPKea_W44U0WfNAs7NA5GwZz3POlGHyDkFh-zjPNBOAA_913_718](https://github.com/alphaess-developer/alphacloud_open_api/assets/117050711/46c540bd-fde2-479f-a0a2-fd58f82063cc)

**Comment by Gaspode69** [comment]
Yes, when I use a worong timestamp, I get also an answer with timestamp error.

But if I send a correct, valid post request to https://openapi.alphaess.com/api/updateChargeConfigInfo I get http error 404.

Please try again with a valid post request.

**Comment by nugget100** [comment]
Please can this issue be reopened as it has been closed in error.

The issue is still active.

**Comment by matt-oneill** [comment]
> ![lQLPKea_W44U0WfNAs7NA5GwZz3POlGHyDkFh-zjPNBOAA_913_718](https://private-user-images.githubusercontent.com/117050711/294467248-46c540bd-fde2-479f-a0a2-fd58f82063cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODExMzEsIm5iZiI6MTcwNDQ4MDgzMSwicGF0aCI6Ii8xMTcwNTA3MTEvMjk0NDY3MjQ4LTQ2YzU0MGJkLWZkZTItNDc5Zi1hMGEyLWZkNThmODIwNjNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxODUzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDg2NDVkZjIwOTliNzRmNzQ2OTY0ZWQxMzg5NzYzODgwY2JkMTNlYThkNjZlZmIzYWIwYjNjNGQwMDExMDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vitep_5UkYwU34dCdYgY35fXClzTqmHazMt-SHZTLLw)

![image](https://github.com/alphaess-developer/alphacloud_open_api/assets/60574293/a7498077-72cb-40c1-aea4-f378e355e219)
