### ISSUE TITLE
getSumDataForCustomer returns wrong values

### ISSUE THREAD

**Issue by Gaspode69** [alphaess-developer/alphacloud_open_api#69]
Since about one week, getSumDataForCustomer returns wrong values for at least two attributes:

- Self_consumption_total
- Self_sufficiency_total

**Comment by Gaspode69** [comment]
In my personal case only Self_consumption_total is wrong (returns 42,2, correct value would be 74,1). Other users report also a wrong value for Self_sufficiency_total.

**Comment by ElevenFan** [comment]
Our platform has updated calculation formulas. I am considering whether to use this openapi. Few people use this value.

**Comment by Gaspode69** [comment]
Please correct the calculation formula for OpenAPI. I know several people who are using this value, including myself.
Currently, the value is correct in the official portal and wrong in the OpenAPI.

**Comment by gbackus** [comment]
I have the same opinion. In the AlphaEss forum, many people use a template of the energiefluss-erweitert-adapter in which the output is used for self-consumption, including me. This display with the wrong value is quite messy.

**Comment by Gaspode69** [comment]
@ElevenFan 
Can you give us an update, please?

**Comment by ElevenFan** [comment]
Done

**Comment by Gaspode69** [comment]
Thank you, but unfortunately Self_consumption_total is still wrong.
Or does the correction need some time to take effect?

**Comment by Gaspode69** [comment]
@ElevenFan 
Still not fixed.

**Comment by Gaspode69** [comment]
Fixed since 21.06.2024
